### ISSUE TITLE
Blosc compression not widely supported

### ISSUE THREAD

**Issue by gustavla** [uchicago-cs/deepdish#10]
The blosc compression (provided by the PyTables backend) is a pretty clear winner:

* http://deepdish.readthedocs.org/en/latest/io.html#sparse-matrices

However, it is not widely supported, so deepdish-saved files won't be loadable through for instance Matlab or h5py. This severely damages the otherwise great portability of HDF5 and can especially be confusing for new users.

I am considering the following solution:

* Make zlib the default compression method. This is much more widely supported (both Matlab and h5py support it, as an example). The compression rate is even slightly better than blosc, but unfortunately it is much slower.
* Add a deepdish config file (maybe `.deepdish.conf` or `.ddrc`) where the default compression can be changed. That way, users that care more about speed than portability can opt-in to blosc without having to specify it every time.

**Comment by gustavla** [comment]
@twmacro If you have any thoughts on this, I'd love your input on it.

**Comment by twmacro** [comment]
Yes, blosc was the clear winner in my trials too with some pretty large real-world datasets. This is definitely a bummer. Right now, I'm still planning to continue using blosc because time is more important to me than portability. (I usually use scipy.io.savemat when I want to port data to Matlab anyway.)

For deepdish defaults, I'm not certain what I would do. Your proposal is certainly reasonable. Leaving it as is with a note in docs seems reasonable to me too. Sorry, I'm not much help!
