### ISSUE TITLE
ValueError when trying to save numpy scalar arrays (ndim = 0)

### ISSUE THREAD

**Issue by craffel** [uchicago-cs/deepdish#16]
```Python
import numpy as np
import deepdish
deepdish.io.save('test.h5', np.array(0.))
```
results in
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

deepdish/io/hdf5io.pyc in save(path, data, compression)
    458
    459         else:
--> 460             _save_level(h5file, group, data, name='data', filters=filters)
    461             # Mark this to automatically unpack when loaded
    462             group._v_attrs[DEEPDISH_IO_UNPACK] = True

deepdish/io/hdf5io.pyc in _save_level(handler, group, level, name, filters)
    184
    185     elif isinstance(level, np.ndarray):
--> 186         _save_ndarray(handler, group, name, level, filters=filters)
    187
    188     elif _pandas and isinstance(level, (pd.DataFrame, pd.Series, pd.Panel)):

deepdish/io/hdf5io.pyc in _save_ndarray(handler, group, name, x, filters)
    112         strtype = None
    113         itemsize = None
--> 114     assert np.min(x.shape) > 0, ("deepdish.io.save does not support saving "
    115                                  "numpy arrays with a zero-length axis")
    116     # For small arrays, compression actually leads to larger files, so we are

numpy/core/fromnumeric.pyc in amin(a, axis, out, keepdims)
   2217         except AttributeError:
   2218             return _methods._amin(a, axis=axis,
-> 2219                                 out=out, keepdims=keepdims)
   2220         # NOTE: Dropping the keepdims parameter
   2221         return amin(axis=axis, out=out)

numpy/core/_methods.pyc in _amin(a, axis, out, keepdims)
     27
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation minimum which has no identity
```

Is saving numpy scalar arrays (`ndim = 0`) supported?  If not, I think you could change the test to 
`assert x.ndim > 0 and np.min(x.shape) > 0`.  The first condition would fail for numpy scalar arrays, so the second wouldn't be evaluated.  If numpy scalar arrays aren't supported, I'm curious why and if that's functionality that could be added.  Finally, separately, you also should arguably be doing
```
if np.min(x.shape) > 0:
    raise ValueError(...)
```
instead of an assert, [see e.g. here](https://github.com/emre/notes/blob/master/python/when-to-use-assert.md), but that's a separate discussion!  Thank you again for the excellent library!

**Comment by gustavla** [comment]
Sorry for not getting to this earlier! Yes, arrays of any size with a 0-length dimension is not supported, since it is not supported by HDF5. However, a scalar array could just be stored as an attribute, just like any Python and numpy scalar would (not scalar array, but just scalar, like `np.int16(100)`. This would cause a slight reconstruction discrepancy, since what you put in is not going to be exactly what you get back.

I rarely even come across scalar arrays in Python, so I'm not entirely certain how to support them properly and whether or not it would be OK to simply save them as scalars. It does seem like numpy scalar arrays and numpy scalars have slightly different semantics (http://stackoverflow.com/questions/773030/why-are-0d-arrays-in-numpy-not-considered-scalar), so does that mean it's important to unpack them correctly?

Maybe you could expand on why you want to save array scalars as opposed to regular scalars, since that could make a difference in how to support them. I'm leaning towards supporting them by extracting the scalar and saving it as an attribute (and unpacking it as a scalar). Possibly with a warning issued.

**Comment by craffel** [comment]
> However, a scalar array could just be stored as an attribute, just like any Python and numpy scalar would (not scalar array, but just scalar, like np.int16(100).

That sounds good, so there's no way to do that currently?

> I rarely even come across scalar arrays in Python, so I'm not entirely certain how to support them properly and whether or not it would be OK to simply save them as scalars.

Hmm.  I think it'd be ok to save it as either a numpy scalar type or a numpy 0d array, as they both have the same API as far as I know off the top of my head.  It wouldn't be ok to save it as a Python scalar, as they have a different API (no shape or ndim attributes, for example).

> Maybe you could expand on why you want to save array scalars as opposed to regular scalars, since that could make a difference in how to support them.

I'd have to loop back on this issue and check.  I think basically I was having an issue where a library I use was storing everything as arrays (even scalars), and when interfacing between it and deepdish I was having these issues.

> I'm leaning towards supporting them by extracting the scalar and saving it as an attribute (and unpacking it as a scalar). Possibly with a warning issued.

That sounds reasonable to me.  It's probably worth finding a set of unit tests for this weird corner case.  I am sure this is not the first time this ambiguity has come up..!

**Comment by gustavla** [comment]
There is no way to store an array scalar no, but regular Python and numpy scalars are supported. However, note that deepdish read every scalar as a numpy scalar, since they have more precise type. So, if you save the Python literal "100", it will be unpacked as a `numpy.int64`, since it was stored as a 8-byte int in the HDF5. If you save 100.0, it will be unpacked as a `numpy.float64`. This is justified by the fact that numpy scalars are essentially supersets of Python scalars (I have yet to encounter a case where I had to convert a numpy scalar to a Python scalar because of incompatibility).

With this in mind, I think it would be fine to have array scalars also be returned back as numpy scalars, even though the difference is bigger than between Python scalars and numpy scalars. I'll try to push a fix to this soon. Thanks for pointing it out!

**Comment by craffel** [comment]
Thanks!  If you want to make a PR or something I can test it out on my problem code to see if there are still any issues on my end (deepdish-related or external library-related).
