### ISSUE TITLE
pip install of deepdish

### ISSUE THREAD

**Issue by CJvanDiepen** [uchicago-cs/deepdish#20]
When installing deepdish under windows (both `pip` and `setup.py`) I get the following error message 

`LINK : fatal error LNK1181: cannot open input file 'hdf5dll.lib'`

How should I install HDF5? I installed the HDF5 software from https://www.hdfgroup.org/HDF5/release/obtain5.html but this did not solve the issue

**Comment by gustavla** [comment]
Hi, I am not a Windows user, but I'll try to give you some suggestions.

First of all, the package that needs HDF5 is PyTables, so to make things easier, I would download PyTables from source and try to install that separately (https://pypi.python.org/pypi/tables). Once it is installed correctly, deepdish should work.

You will need to figure out where HDF5 was installed (search for it?). Once you know this, you can run the PyTables installation with:

    python setup.py install --hdf5=/path/to/hdf5

I guess that should probably be something like `C:\path\to\hdf5`, but you get my point. Alternatively, you might be able to add the HDF5 directory to the appropriate environment variable (on Linux, this would be `LD_LIBRARY_PATH`, but on Windows it might be `PATH`, but I am not sure). If that doesn't work, you could reach out to the PyTables community for help, since they might have a more experienced Windows user that can guide you through it.

**Comment by gustavla** [comment]
Actually, not sure if my instructions were correct for Windows. Take a look a this:

www.pytables.org/usersguide/installation.html

They have plenty of information for how to install under Windows.
